### ISSUE TITLE
Ukol 01 baliky

### ISSUE THREAD

**Issue by LenkaHavlickova** [LenkaHavlickova/python-kurz-2022#1]
https://github.com/LenkaHavlickova/python-kurz-2022/blob/main/ukol01_baliky.py

Ahoj Jirko, posilam odkaz na ukol 01. Omlouvam se za to rozsireni. (Bavi me to.) Uvitam jakekkoliv rady ci tipy.

Dik Lenka

**Comment by bromjiri** [comment]
Ahoj Lenko :) 
dobrá práce a zajímavé rozšíření 👍 
Ani mě nenapadá, co bych k tomu dal za radu. Možná jenom z hlediska čtení a srozumitelnosti kódu by bylo hezčí jej rozdělit do funkcí, asi ideálně do dvou. První by se jmenovala něco jako "package_check" a druhá "package_change". Obě funkce by jako vstupní parametr braly číslo balíku.
Ale i bez funkcí je to dobře čitelné. Dobrá práce :)

**Comment by LenkaHavlickova** [comment]
Ahoj, mockrát děkuju za tip. Nedalo mi to a nějak jsem doplnila i ty funkce.  Díky
