### ISSUE TITLE
Úkol 10 Teplota ve městech

### ISSUE THREAD

**Issue by LenkaHavlickova** [LenkaHavlickova/python-kurz-2022#10]
Ahoj Jirko, 

posílám odkaz na úkol 10.

https://github.com/LenkaHavlickova/python-kurz-2022/blob/main/ukoly/ukol10_teplota_mesta.py

V posledním úkolu, kde se mají hledat záznamy pro města "Washington" a "Philadelphia", je ve výsledku hledání Washington 2x (Washington a Washington DC). Kdybych chtěla upravit dotaz tak, aby vzal pouze přesné zadaní, tedy pouze "Washington", musím na to jít přes regulární výrazy, nebo to jde i jinak?

Přeju pěkný víkend

Lenka

**Comment by LenkaHavlickova** [comment]
Tak omyl.  Překoukla jsem se. Zjistila jsem, že v souboru jsou hodnoty pro Washington (btw i pro Washington DC) dvakrát. Tudíž jsem doplnila drop_duplicates.

Lenka

**Comment by bromjiri** [comment]
Ahoj Lenko,

úkol máš vyřešený dobře. V praxi bych pak doporučoval se různých duplikátů a nechtěných dat zbavit hned na začátku, aby jednotlivé výsledky byly porovnatelné a konzistentní. 
Například záznamy s teplotou -99 nám tam dělají docela problém, takže je lepší je odebrat hned na začátku například pomocí příkazu drop, do kterého se jako argument dá index nechtěných řádků:
`temp_file = temp_file.drop(temp_file[temp_file['AvgTemperature'] == -99].index)`

Každopádně dobrá práce 👍

**Comment by LenkaHavlickova** [comment]
Super, děkuju. L.
