### ISSUE TITLE
Úkol 11 Zaměstnanci projekty

### ISSUE THREAD

**Issue by LenkaHavlickova** [LenkaHavlickova/python-kurz-2022#11]
Ahoj Jirko,

posílám odkaz na úkol č. 11.

https://github.com/LenkaHavlickova/python-kurz-2022/blob/main/ukoly/ukol11_zamestnanci_projekty.py

Akorát jsem si všimla (pokud jsem se někde nespletla), že hodiny na projektech za únor vykázali i bývalí zaměstnanci, kteří už za únor nedostali plat. :-) Nechala jsem tyhle podezřelé hodiny ve statistice za jednotlivé kanceláře, ale můžu je případně vyndat, 

Měj se krásně

Lenka

**Comment by bromjiri** [comment]
Ahoj Lenko

máš pravdu, jsou tam vykázané hodiny za únor od bývalých zaměstnanců. Těžko říct, jestli je to chyba zadání nebo záměr.. každopádně jsi to vyřešila skvěle. 
Nemám k tomu žádný komentář - zmíněné příkazy jdou napsat i jinak, ale nevím o žádném vyloženě efektivnějším řešení.
Dobrá práce 👍

**Comment by LenkaHavlickova** [comment]
Mockrát děkuju, Jirko. Lenka
