### ISSUE TITLE
Úkol 12 Vizualizace

### ISSUE THREAD

**Issue by LenkaHavlickova** [LenkaHavlickova/python-kurz-2022#12]
Ahoj Jirko,

omlouvám se, určitě už sis myslel, že už budeš mít pokoj :-), ale posílám ještě ten poslední úkol.

https://github.com/LenkaHavlickova/python-kurz-2022/blob/main/ukoly/ukol12_vizualizace.py

Díky

Lenka

**Comment by bromjiri** [comment]
Ahoj Lenko :) 
řešení máš jako vždy správně. Jediný tip, co mě napadá je, že když děláš histogram, tak nemusíš dropovat ty nepotřebné sloupce, stačí pouze vybrat ten jeden potřebný sloupec a na něm udělat histogram, výsledek je prakticky stejný. Teda jedinný rozdíl je v tom, že tvé řešení vloží název sloupce nad výsledný graf, ale to lze doplnit pomocí `plt.title` a třeba tam i přidat jednotku.

```
wages = pd.read_csv("ukoly/platy_2021_02.csv")
wages['plat'].hist(bins=[30000, 35000, 40000, 45000, 50000, 55000, 60000])
plt.title("plat [CZK]")
```

Dobrá práce 👍 
Jinak přeju ať ti vydrží motivace k dalšímu učení Pythonu, jde ti to dost rychle. Evidentně tě to baví, což je 99% úspěchu k tomu být dobrý programátor :)
Měj se a užij si léto :)

**Comment by LenkaHavlickova** [comment]
Ahoj Jirko, 

děkuju za další dobrou radu.👍 A ještě rovnou mockrát děkuju za všechny dosavadní rady a tipy, tvůj čas a taky za podporu. ♥️

Měj se krásně

Lenka
