### ISSUE TITLE
Úkol 02 Státy světla

### ISSUE THREAD

**Issue by LenkaHavlickova** [LenkaHavlickova/python-kurz-2022#2]
https://github.com/LenkaHavlickova/python-kurz-2022/blob/main/ukol2_staty_sveta.py

Ahoj, posílám odkaz na druhý úkol.

Lenka

**Comment by bromjiri** [comment]
Ahoj Lenko,
dobrá práce. Nemám, co bych k tomu vytknul :)

**Comment by LenkaHavlickova** [comment]
Děkuju mockrát. L.
