### ISSUE TITLE
Úkol 03 SMS brána ve dvou verzích

### ISSUE THREAD

**Issue by LenkaHavlickova** [LenkaHavlickova/python-kurz-2022#3]
Ahoj, 

prvně posílám odkaz na úkol dle zadání:
https://github.com/LenkaHavlickova/python-kurz-2022/blob/main/ukol03_sms_brana.py

Pak jsem si zkusila stáhnout tu knihovnu. I když přiznávám, že na obsah použitých funkcí jsem jukla jen velmi letecky a nedám ruku do ohně za to, že to dělá přesně to, co chci. :-)
https://github.com/LenkaHavlickova/python-kurz-2022/blob/main/ukol03_sms_brana_library.py

Ze zvědavosti, když bys soubor stahoval k sobě, musíš si asi taky nainstalovat knihovnu phonenumbers, že ano?

Děkuju Lenka

**Comment by bromjiri** [comment]
Ahoj Lenko,
tvé řešení vypadá dobře, ještě na to podrobněji kouknu po dnešní lekci. 
Celkem dobrý příklad o funkcích zmíněné knihovny jsem našel tady:
https://stackabuse.com/validating-and-formatting-phone-numbers-in-python/#:~:text=let%27s%20start%20with-,is_possible_number,-()%3A

Abych odpověděl na tvůj dotaz ohledně instalace knihovny:
Máš pravdu, musím si ji nainstalovat také. V případě jedné malé knihovny to není problém, ale asi si umíš představit, že někdo může napsat program, kde používá desítky knihoven a ještě k tomu je důležité dodržet konkrétní verze knihoven. 
V takovém případě se nabízí několik možných řešení, například:

- použití souboru requirements.txt
  - když zadáš do příkazové řádky `pip freeze`, vypíše ti to seznam všech tvých knihoven, které máš nainstalované
  - pomocí `pip freeze > requirements.txt` můžeš seznam tvých knihoven uložit do souboru a tento soubor poslat člověku, který si chce tvůj program spustit ve stejném prostředí, jako máš ty
  - příjemce tvého souboru si potom může jednoduše nainstalovat tvé knihovny pomocí `pip install -r requirements.txt`
  - pokud si příjemce nechce zaplácat svůj Python různýma knihovnama, může si pomocí programu Anaconda nainstalovat virtuální Python prostředí, které později jednoduše smaže

- použití Docker
  - tohle už je trochu komplikovanější, ale v současné době je to ve firmách moderní
  - Docker je program, který umí tvůj program zabalit do tzv. image, který pošleš někomu jinému, který si jej snadno spustí bez dalších instalací, pokud sám má také Docker

**Comment by LenkaHavlickova** [comment]
Super, mockrát děkuju za tipy! 👍

**Comment by bromjiri** [comment]
Ahoj Lenko, 
ještě jsem dodatečně koukal na třetí úkol. 
Obě řešení jsou dobrá a splňují zadání.

U řešení s knihovnou "phonenumbers" mám pocit, že řádky 11-13 jsou zbytečné. Používáš tam dvě rozdílné funkce na kontrolu čísla. `is_valid_number` je přísnější, zatímco přes `is_possible_number` projde i neexistující číslo, které má alespoň správný číselný formát. Tím, že máš jako první v podmínce `is_valid_number`, myslím, že na kontrolu pomocí `is_possible_number` prakticky nikdy nedojde.
Ale to je jen detail :)

Každopádně dobrá práce, úkol splněn a zavírám issue 👍
