### ISSUE TITLE
Úkol 04 Evidence aut

### ISSUE THREAD

**Issue by LenkaHavlickova** [LenkaHavlickova/python-kurz-2022#4]
Ahoj Jirko,

posílám odkaz na úkol č. 4:
https://github.com/LenkaHavlickova/python-kurz-2022/blob/main/ukol04_autopujcovna.py

Snad jsem ten kód moc nezkomplikovala. Za tipy budu opět vděčná. Na řádku 39 jsem si pomohla funkcí exit(), jinak by mi v případě zadání neplatné hodnoty uživatelem padal program do chyby. Určitě to jde udělat nějak líp, ale z ošetřování výjimek mám respekt. Nebo to jde nějak jednoduše?

Díky Lenka

**Comment by bromjiri** [comment]
Ahoj Lenko,

tvoje řešení určitě dobré, v případě vstupu z příkazové řádky to moc lépe nejde. V reálu by se samozřejmě podobný rezervační systém dělal pomocí nějaké webové stránky, která by uživateli umožnila vybrat pouze Škoda nebo Peugeot, takže by nebylo možné zadat špatný vstup a exit() by nebylo potřeba.
Pro náš příklad však máme vstup z příkazové řádky a tam se uživatel nedá nijak omezit, takže je potřeba počítat s chybným vstupem. Řešení pomocí exit je jedna z mnoha možností, ale spíše by se něco podobného řešilo pomocí další podmínky, případně pomocí try-except funkcí.

Já bych to asi zbytečně nekomplikovat a prostě bych v případě špatného vstupu vracel nějakou třetí hodnotu, kterou bych následně kontroloval v té volající funkci:

```
def volba_auta(pozadovane_auto):
    # Funkce prevadi textovy vstup uzivatele na konretni zadany objekt
    if pozadovane_auto == "Škoda":
        return (skoda)
    elif pozadovane_auto == "Peugot":
        return (peugot)
    else:
        return None


def pujceni_auta():
    pozadovane_auto = volba_auta(input(
        "Jaké auto si přejete půjčit? (Škoda/Peugot): "))  # vstup uzivatele: typ vozu, pomoci fce volba_auta preklad na konkretni objekt
    if pozadovane_auto is None:
        print(f"Vámi uvedené vozidlo není v naší nabídce.")
    else:
        print(pozadovane_auto)
        pozadovane_auto.pujc_auto()
```

Dále by se v kódu nabízelo podobným způsobem opravit další uživatelské vstupy, jako například když uživatel zadá počet najetých km něco jiného než číslo. Ale to už je v tomto případě také jenom detail.

Dobrá práce 👍

**Comment by LenkaHavlickova** [comment]
Mockrát děkuju. Lenka
