### ISSUE TITLE
Úkol 05 streamovací služba

### ISSUE THREAD

**Issue by LenkaHavlickova** [LenkaHavlickova/python-kurz-2022#5]
Ahoj Jirko,

posílám odkaz na další úkol.

https://github.com/LenkaHavlickova/python-kurz-2022/blob/main/ukol05_streamovaci_sluzba.py

Samotnou mě překvapilo, že se mi podařilo v metodě ve třídě User pracovat s metodami a atributy z jiné třídy (ř. 57 - 59). Ještě mě napadlo neuchovávat u uživatele pouze seznam titulů viděných položek, ale seznam celých objektů, akorát už se mi v metodě __str__() nějak nepodařilo pracovat s jednotlivými atributy objektů jiné třídy (např. doptat se na titul přes item.titul). Asi je to tím, že v argumentech __str__ je jen self a nevím, kam bych protlačila typování, že item je objektem třídy Item, jako na řádku 57. 

Opět uvítám tipy, rady.

Děkuju Lenka

**Comment by bromjiri** [comment]
Ahoj Lenko,

dobrá práce, úkol přesně splňuje zadání 👍 
Pokud si dobře pamatuju, tak tvůj dotaz zodpověděla Lída přímo na poslední lekci, je to tak? 

Jinak chválím za použití Abstract class. Ke kódu asi nemám co vytknout. :)

**Comment by LenkaHavlickova** [comment]
Ahoj Jirko, moc děkuju. Ano, Lída dotaz zodpověděla. Vyzkoušela jsem a funguje to. Nechala jsem se původně odradit nápovědou VS Code (volaná metoda jiné třídy zůstala nezabarvená, jakože neznámá) :-)

https://github.com/LenkaHavlickova/python-kurz-2022/blob/main/ukoly/ukol05_streamovaci_sluzba.py

Pěkný víkend

Lenka
