### ISSUE TITLE
Úkol 06 Půjčovna aut

### ISSUE THREAD

**Issue by LenkaHavlickova** [LenkaHavlickova/python-kurz-2022#6]
Ahoj Jirko,

posílám odkaz na domácí úkol č. 6.

https://github.com/LenkaHavlickova/python-kurz-2022/blob/main/ukoly/ukol06_pujcovna_aut.py

Měj se pěkně

Lenka

**Comment by bromjiri** [comment]
Ahoj Lenko
tvé řešení je správně. Navíc jsi jej zvládla napsat na docela málo řádků a celkem efektivně. Dobrá práce 👍 

Moc mě nenapadá, co k tomu vytknout. Snad jenom, že v reálu bych se na řádku 2 úplně nespoléhal na to, že všechny soubory mají příponu dlouhou 3 znaky. Například pro .docx by to nefungovalo. Ale to je jen detail..

Jirka

**Comment by LenkaHavlickova** [comment]
Ahoj, moc děkuju. S těmi příponami jsem to teda nedomyslela, to máš pravdu. Děkuju.

Lenka
