### ISSUE TITLE
Úkol 07 Pošta

### ISSUE THREAD

**Issue by LenkaHavlickova** [LenkaHavlickova/python-kurz-2022#7]
Ahoj Jirko,

posílám odkaz na úkol č. 7:

https://github.com/LenkaHavlickova/python-kurz-2022/blob/main/ukoly/ukol07_posta.py

Nevím, jestli je to žádoucí, ale zkusila jsem ze seznamu adres odstranit duplicity. Jinak rovnou přiznávám, že si tentokrát nejsem řešením moc jistá. Při nahrazování víc mezer jednou mezerou, jsem použila  \s i když vím, že to nejsou jen mezery, ale přišlo mi, že to není v rozporu se zadáním. No, nevím. :-)

Lenka

**Comment by bromjiri** [comment]
Ahoj Lenko,

řešení vypadá v pořádku. Použití /s na odebrání mezer určitě nevadí, pokud tam jsou nějaké taby a další whitespaces, tak je určitě lepší je nahradit také. Chválím za odebrání duplicit 👍 

Mimochodem, duplicity jsou trochu kratším kódem odebrat také následovně:
`psc_list_unique = list(set(psc_list))`
`set` automaticky odebírá duplicity, akorát nedodržuje pořadí.

Dobrá práce :)

**Comment by LenkaHavlickova** [comment]
Děkuju
