### ISSUE TITLE
Úkol 08 Letní kino

### ISSUE THREAD

**Issue by LenkaHavlickova** [LenkaHavlickova/python-kurz-2022#8]
Ahoj Jirko,

posílám odkaz na úkol č. 8.

https://github.com/LenkaHavlickova/python-kurz-2022/blob/main/ukoly/ukol08_letni_kino.py

Měj se krásně

Lenka

**Comment by bromjiri** [comment]
Ahoj Lenko,

řešení a práce s datetime je v pořádku. K postupu mám pouze pár tipů:

Z prvotní informace uživatel nemusí pochopit, že je požadována mezera za tečkami. Tam by pomohlo odebrat případné mezery, jak jsme se to učili v části regulární výrazy (např. pomocí `replace`), a načítat vstup bez mezer. Tím umožníš uživateli použít i nepoužít mezery a je větší šance, že se trefí. 

Pokud se i tak uživatel netrefí do požadovaného formátu, vyskočí error. Tuto kontrolu můžeme provést sami a v případě špatného vstupu vytisknout poněkud "lépe" vypadající hlášku pomocí tzv. bloku `try-except`. To jsme sice ještě nebrali, ale ty to určitě rychle pochopíš. https://www.w3schools.com/python/python_try_except.asp

Jinak dobrá práce 👍

**Comment by bromjiri** [comment]
try except blok může vypadat například takto:

```
try:
    require_date_f = datetime.strptime(require_date, "%d. %m. %Y")
except ValueError:
    print("Incorrect data format, should be DD. MM. YYYY")
    exit()
```

**Comment by LenkaHavlickova** [comment]
Ahoj Jirko,

mockrát děkuju. Super tipy. Zapracovala jsem, doplnila do kódu.

Lenka
