### ISSUE TITLE
Úkol 09 Adopce zvířat

### ISSUE THREAD

**Issue by LenkaHavlickova** [LenkaHavlickova/python-kurz-2022#9]
Ahoj Jirko,

posílám odkaz na úkol č. 9.

https://github.com/LenkaHavlickova/python-kurz-2022/blob/main/ukoly/ukol09_adopce_zvirat.py

Měj se pěkně

Lenka

**Comment by bromjiri** [comment]
Ahoj Lenko,

úkol je správně. Šlo o základy pandasu, takže tady nemám moc tipů, co bych vytkl :)
Dobrá práce 👍

**Comment by LenkaHavlickova** [comment]
Ahoj Jirko, děkuju. Lenka
